### ISSUE TITLE
Missing numerous MySql keywords

### ISSUE THREAD

**Issue by bavalpey** [textmate/sql.tmbundle#25]
I noticed that quite a few keywords from MySQL and even TSQL are missing. I also notice there are outstanding pull requests that have not been merged that add to some of the syntax highlighting, which have been outstanding for more than a year.  Is this repository still maintained?

**Comment by sorbits** [comment]
You are correct in your observation that there is no active maintainer of this bundle.

Though personally I would prefer the SQL grammar adhere to the standard (which would be SQL:2016) rather than add vendor specific syntax.

Vendor specific syntax could be added as an injection grammar that users of that vendor’s product could then enable.

**Comment by bavalpey** [comment]
This isn't helpful.  Github's syntax highlighting for SQL depends on this repo.  There are pull requests to add new keywords to this that are not going through.  This should be maintained, or should be passed off so that Linguist can use a different repo for its syntax highlighting for SQL
